name: Upload Files to Another Repository

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"

      - name: Copy files to destination repository
        run: |
          mkdir upload_temp
          cp -r * upload_temp/
          cd upload_temp
          git init
          git remote add destination-repo https://github.com/MoeinAbtahi/Software-Engineering-Studio-ENGR5590G-Peresntation-Clone.git
          git add .
          git commit -m "Upload files to destination repository"
          git push -f destination-repo main  # Adjust branch name if needed
