name: Sync to Repository B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository A
      uses: actions/checkout@v2

    - name: Print Git Remote Info
      run: |
        git remote -v

    - name: Push to Repository B
      env:
        GH_PAT_B: ${{ secrets.GH_PAT_B }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        git remote remove origin || true
        
        git remote add origin https://x-access-token:${{ secrets.GH_PAT_B }}@github.com/MoeinAbtahi/Software-Engineering-Studio-ENGR5590G-Peresntation-Clone.git
        
        git remote -v  # Check remote URL configuration
        
        git add .
        git commit -m "Sync from Repository A" || true
        
        git push -u origin main --force
