name: Sync to Repository B

on:
  push:
    branches:
      - main  # Adjust this if you want to trigger on a different branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository A
      uses: actions/checkout@v2

    - name: Push to Repository B
      env:
        GH_PAT_B: ${{ secrets.GH_PAT_B }}
      run: |
        # Set up git configuration
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Remove existing remote if it exists
        git remote remove origin || true
        
        # Add new remote for Repository B
        git remote add origin https://x-access-token:${{ secrets.GH_PAT_B }}https://github.com/MoeinAbtahi/Software-Engineering-Studio-ENGR5590G-Peresntation-Clone.git
        
        # Add and commit all files
        git add .
        git commit -m "Sync from Repository A" || true
        
        # Force push to the target repository
        git push -u origin main --force
